# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  templatedotnetapi:
    image: templatedotnetapi
    build:
      context: .
      dockerfile: src/TemplateDotNet.Api/Dockerfile
    ports:
      - 5001:5001
